app = "escrow-bot"

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  image = "registry.fly.io/escrow-bot:deployment-cuzcuz"  # 실제 태그로 변경

[env]
  TELEGRAM_API_KEY = "your_telegram_bot_token"
  DATABASE_URL = "postgresql://postgres:your_password@escrow-bot-db.flycast:5432/escrow_bot?sslmode=disable"
  TRON_API = "https://api.trongrid.io"
  TRON_API_KEY = "your_tron_api_key"
  PRIVATE_KEY = "your_private_key"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  [[services.ports]]
    handlers = ["http"]
    port = 80