app = "escrow-bot"

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  image = "registry.fly.io/escrow-bot:deployment-{{your_commit_hash}}"


[experimental]
  auto_rollback = true

[[services]]
  # 텔레그램 봇은 polling 방식이므로 포트를 사용하지 않지만,
  # fly.io에서는 내부적으로 health check 등을 위해 포트를 열 수 있습니다.
  internal_port = 8080
  protocol = "tcp"
  [services.concurrency]
    type = "connections"
    soft_limit = 25
    hard_limit = 30